[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/deploy"
  to = "/.netlify/functions/deploy"
  status = 200

[[redirects]]
  from = "/template/*"
  to = "/template/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
